config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :classrooms do
    get :classroom_students 
    resources :students, only: [:create]
    resources :tasks do
      patch 'update_progress', on: :member
      patch 'update_time_spent', on: :member
      resources :feedbacks, only: [:index, :create]
      get :students_progress
    end
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :classroom
  get '/sobre', to: 'pages#about', as: :about
  get 'notifications', to: 'notifications#index', as: :notifications
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :classroom_enrollments, dependent: :destroy
  has_many :users, through: :classroom_enrollments
  has_many :tasks
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[ show edit update destroy classroom_students]

  # GET /classrooms or /classrooms.json
  def index
    @classrooms = current_user.user_type == 'Aluno' ? current_user.classrooms : Classroom.where(author_id:current_user.id)
  end

  # GET /classrooms/1 or /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms or /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.author_id = current_user.id

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_path, notice: "Turma Criada com Sucesso." }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1 or /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classrooms_path, notice: "Turma Atualizada com Sucesso." }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1 or /classrooms/1.json
  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Turma Excluida com Sucesso." }
      format.json { head :no_content }
    end
  end

  def classroom_students
    @students = @classroom.users
  end 

  private

    def set_classroom
      @classroom = params[:id].nil? ? Classroom.find(params[:classroom_id]) : Classroom.find(params[:id])
    end

    def classroom_params
      params.require(:classroom).permit(:name, :author_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_classroom.html.erb
<div id="<%= dom_id classroom %>">
  <p>
    <strong>Name:</strong>
    <%= classroom.name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= classroom.author_id %>
  </p>

</div>

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom) do |form| %>
  <% if classroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
        <% classroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/classroom_students.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Students Progress - <%=  %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_tag 'application' %>

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container mt-5">
      <div class="mb-4">
      <% available_students = User.where(user_type: 'Aluno').where.not(id: @classroom.users.pluck(:id)) %>
      <%= form_with url: classroom_students_path(@classroom), method: :post, local: true do |f| %>
        <div class="form-group row">
          <div class="col-md-8">
            <%= f.collection_select :user_id, available_students, :id, :name, prompt: "Selecione um aluno", class: "form-control" %>
          </div>
          <div class="col-md-4">
            <%= f.submit "Adicionar à Turma", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    <table class="table table-striped mt-4">
      <thead>
        <tr>
          <th>Nome do aluno</th>
          <th>Nível de escolaridade</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= Task::TRANSLATED_GRADES[student.grade_level] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/classrooms/edit.html.erb
<h1>Editando Turma</h1>
<div class="mb-3">
  <%= link_to "Turmas", classrooms_path, class: "btn btn-secondary" %>
</div>
<%= form_with(model: @classroom, local: true) do |f| %>
  
  <div class="mb-3">
    <%= f.label 'Nome', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= f.submit "Salvar", class: 'btn btn-primary' %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Mostrar Turma", @classroom %> |
  <%= link_to "Turmas", classrooms_path %>
</div>

app/views/classrooms/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourAppName</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_tag 'application' %>

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

</head>
<body class="bg-light">
  <div class="container mt-5">
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
    
    <h1 class="mb-4">Turmas</h1>

    <div id="classrooms" class="row">
      <% @classrooms.each do |classroom| %>
        <div class="col-md-4 mb-4">
        <%p 'ai dentrooo'%>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= classroom.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted">Professor: <%= classroom.author.name %></h6>
              <%= link_to "Ver Textos", classroom_tasks_path(classroom), class: "btn btn-info" %>
              <% if current_user.id == classroom.author_id %>
                <%= link_to "Editar Turma", classroom_path(classroom), class: "btn btn-primary" %>
                <%= link_to "", classroom_classroom_students_path(classroom), class: "fas fa-user-plus" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <% if current_user.user_type == 'Professor' %>
      <%= link_to "Nova Turma", new_classroom_path, class: "btn btn-success mt-4" %>
    <%end%>
  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/classrooms/new.html.erb
<h1>Nova Turma</h1>

<%= form_with(model: @classroom, local: true) do |f| %>
  
  <div class="mb-3">
    <%= f.label 'Nome', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= f.submit "Criar Turma", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/classrooms/show.html.erb
<p style="color: green"><%= notice %></p>

  <div class="mb-3">
  <%= link_to "Turmas", classrooms_path, class: 'btn btn-secondary' %> 
</div>

<div class="mb-3">
  <h5 class="form-control">Nome: <%= @classroom.name %></h5>
</div>

<div>
  <div class="mb-3">
  <%= link_to "Editar turma", edit_classroom_path(@classroom), class: 'btn btn-primary' %> 
  </div>
  <div class="mb-3">
  <%= button_to "Excluir Turma", @classroom, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this classroom?" } %>
  </div>
</div>