config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :classrooms do
    get :classroom_students 
    resources :students, only: [:create]
    resources :tasks do
      patch 'update_progress', on: :member
      patch 'update_time_spent', on: :member
      resources :feedbacks, only: [:index, :create]
      get :students_progress
    end
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :classroom
  get '/sobre', to: 'pages#about', as: :about
  get 'notifications', to: 'notifications#index', as: :notifications
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :classroom_enrollments
  has_many :classrooms, through: :classroom_enrollments
  has_many :task_progresses

  enum grade_level: { fifth_grade: 0, sixth_grade: 1, seventh_grade: 2, eighth_and_nineth_grade: 3,tenth_to_twelveth_grade: 4, college: 5, college_graduate: 6, professional: 7 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def show
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Usuario criado com sucesso"
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuario Atualizado com Sucesso' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :grade_level, :user_type)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def translate_user_type
    { 
      "Professor" => "Professor",
      "Aluno" => "student"
    }
  end
end

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sharks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourAppName</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_tag 'application' %>

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <%= form_with(model: @user, url: users_path, local: true, class: "needs-validation", novalidate: true) do |form| %>
          <div class="mb-3">
            <%= form.label 'Nome', class: 'form-label' %>
            <%= form.text_field :name, class: 'form-control', required: true %>
          </div>

          <div class="mb-3">
            <%= form.label 'Email', class: 'form-label' %>
            <%= form.email_field :email, class: 'form-control', required: true %>
          </div>

          <div class="mb-3">
            <%= form.label 'Senha', class: 'form-label' %>
            <%= form.password_field :password, class: 'form-control', required: true %>
          </div>

          <div class="mb-3">
            <%= form.label 'Confirmação de senha', class: 'form-label' %>
            <%= form.password_field :password_confirmation, class: 'form-control', required: true %>
          </div>

          <div class="mb-3">
            <%= form.label 'Tipo de usuário', class: 'form-label' %>
            <%= form.select :user_type, ['Aluno', 'Professor'], {}, class: 'form-select' %>
          </div>

          <div class="mb-3">
            <%= form.label 'Nível de escolaridade', class: 'form-label' %>
            <%= form.select :grade_level, translate_grades, {}, class: 'form-select' %>
          </div>

          <div class="mb-3">
            <%= form.submit "Criar Usuário", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/show.html..erb
<%= content_tag :h1, current_user.welcome %>
<%= link_to "Sign out", session_path, method:"delete" %>